#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["src/services/service1/Service1.API/Service1.API.csproj", "src/services/service1/Service1.API/"]
RUN dotnet restore "src/services/service1/Service1.API/Service1.API.csproj"
COPY . .
WORKDIR "/src/src/services/service1/Service1.API"
RUN dotnet build "Service1.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Service1.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Service1.API.dll"]